### ISSUE TITLE
Support HttpClient 4.3.x, Removing Deprecated HttpClient methods and classes

### ISSUE THREAD

**Issue by phasebash** [jgritman/httpbuilder#21]
This request is to update httpbuilder to use the most recent HttpClient APIs.  Notable changes include the removal of HttpParams as a way of configuring settings (this is now RequestConfig), removing deprecated interfaces and abstract/concrete classes (HttpClient, DefaultHttpClient, AbstractHttpClient), and making sure httpbuilder uses non-deprecated CloseableHttpClient methods.

**Comment by juwi** [comment]
+1 
HttpClient > 4.3.2 would also bring SNI support which would make the Library much more useful in Loadbalanced environments. Can't really encourage ignoreSSLIssues() as a workaround.

**Comment by gregorydickson** [comment]
I just forked to http://github.com/gregorydickson/httpbuilder and I am going to try and do this upgrade
