### ISSUE TITLE
Once Concern in implementation of REST Client

### ISSUE THREAD

**Issue by LamaBimal** [jgritman/httpbuilder#67]
I am using REST client to recieve a arrayBuffer from REST API in my frontEnd Application. But I am not getting the expected response from the RESTClient. Does REST Client parsed the data internally or not?
I am getting the expected result from the browser while hitting through the frontEnd javascript without the involvement of RESTClient.

**Comment by genevaya** [comment]
Hello ::  
Thanks for the RESTClient ... code is giving error; I pasted the code as is in my Eclipse IDE. Getting a Caught: groovyx.net.http.HttpResponseException: Bad Request
groovyx.net.http.HttpResponseException: Bad Request

I am getting the same result when I hit my own internal REST server; then as a test, I copied the exact example of Twitter shown in this page. 
 BTW ... thanks for your effort to keep this page updated. 

Please help!
thanks / sanjiv
[RESTClient_error-1.pptx](https://github.com/jgritman/httpbuilder/files/671549/RESTClient_error-1.pptx)

**Comment by LamaBimal** [comment]
Hello @genevaya,
Have you found any solution for the issues?
