### ISSUE TITLE
HTTPBuilder.ignoreSSLIssues() is not working

### ISSUE THREAD

**Issue by jainishshah17** [jgritman/httpbuilder#71]
No signature of method: groovyx.net.http.HTTPBuilder.ignoreSSLIssues() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: groovyx.net.http.HTTPBuilder.ignoreSSLIssues() is applicable for argument types: () values: []

**Comment by jainishshah17** [comment]
Changes issuename

**Comment by mchiareli** [comment]
you may be using a old version, try with 0.7.2

**Comment by kenwdelong** [comment]
I do not find 0.7.2 in Maven Central or JCenter.  But I see the tag in Github.  Is this something we need to build ourselves?

**Comment by mchiareli** [comment]
you right, i can resolve 0.7.2 using grab, but i am not sure the repository is being used, i can confirm ignoreSSLIssues is working with 0.7.1 as well, you good to use that version.

**Comment by jainishshah17** [comment]
It worked after I manually downloaded 0.7.1 version.
