### ISSUE TITLE
old dependencies

### ISSUE THREAD

**Issue by sarah-jay-peper** [jgritman/httpbuilder#80]
httpbuilder is using indirectly an old version of commons-collections (3.2.1) that is flagged as unsafe, which is included from the really old version of net.sf.json-lib:json-lib (from 2010). We would like to continue using httpbuilder, so we'd be happy to assist getting this updated. But I have not worked on this project before

**Comment by markhu** [comment]
Have you tried updating the version for the JSON lib in the pom.xml file?

**Comment by cjstehno** [comment]
Consider taking a look at [HttpBuilder-NG](https://http-builder-ng.github.io/http-builder-ng/) - it was originally a fork of this project and it is modernized and actively developed.
